version: '3.8'

services:
  # PHP-FPM service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: krayin-crm-app
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=krayin_crm
      - DB_USERNAME=krayin
      - DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - krayin-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: krayin-crm-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - krayin-network

  # MySQL database
  db:
    image: mysql:8.0
    container_name: krayin-crm-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: krayin_crm
      MYSQL_USER: krayin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - krayin-network

  # Redis for caching (optional)
  redis:
    image: redis:alpine
    container_name: krayin-crm-redis
    ports:
      - "6380:6379"
    networks:
      - krayin-network

volumes:
  db_data:

networks:
  krayin-network:
    driver: bridge
