name: Build shared-hosting ZIP

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, gd, bcmath, zip, pdo_mysql
          coverage: none

      - name: Install Composer deps
        run: composer install --no-dev --optimize-autoloader --prefer-dist --ignore-platform-req=ext-calendar --no-interaction --no-ansi --no-progress

      - name: Build assets
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci || npm install
      - run: npm run build

      - name: Inject .env from secret (optional)
        if: ${{ secrets.ENV_FILE != '' }}
        run: |
          printf "%s" "${ENV_FILE}" > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Prune vendor to reduce size (safe)
        run: |
          # Remove VCS metadata only (safe)
          find vendor -type d -name ".git" -prune -exec rm -rf {} +

      - name: Prepare artifact
        run: |
          if [ ! -f .env ]; then cp .env.example .env; fi
          php artisan key:generate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          rm -rf storage/logs/*
          mkdir -p storage/framework/{cache,data,sessions,views}
          mkdir -p public/storage
          composer dump-autoload -o

      - name: Zip app (max compression)
        run: |
          zip -r -9 krayin-shared.zip \
            app bootstrap config database public resources routes vendor artisan \
            composer.json composer.lock package.json package-lock.json vite.config.js \
            storage/lang storage/app/.gitignore storage/framework storage/logs/.gitignore \
            .env \
            packages \
            --exclude "public/admin/build/*" --exclude "node_modules/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: krayin-shared
          path: krayin-shared.zip

      - name: Install lftp
        if: ${{ secrets.FTP_HOST != '' && secrets.FTP_USER != '' && secrets.FTP_PASS != '' }}
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via FTP (InfinityFree)
        if: ${{ secrets.FTP_HOST != '' && secrets.FTP_USER != '' && secrets.FTP_PASS != '' }}
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          lftp -u "$FTP_USER","$FTP_PASS" "$FTP_HOST" -e "
          set ftp:passive-mode on;
          set ftp:ssl-allow yes;
          set ssl:verify-certificate no;
          set net:max-retries 2;
          set net:timeout 20;
          lcd ${GITHUB_WORKSPACE};
          cd htdocs;
          mirror -R --parallel=4 --verbose --only-newer \
            --exclude-glob .git* \
            --exclude-glob node_modules \
            --exclude-glob .github \
            --exclude-glob "*.map" \
            . .;
          bye"

